/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ChildRouteImport } from './routes/child'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as FrequencyRouteImport } from './routes/frequency'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRoute = ChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequencyRoute = FrequencyRouteImport.update({
  id: '/frequency',
  path: '/frequency',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/child': typeof ChildRoute
  '/conversation': typeof ConversationRoute
  '/devices': typeof DevicesRoute
  '/frequency': typeof FrequencyRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/child': typeof ChildRoute
  '/conversation': typeof ConversationRoute
  '/devices': typeof DevicesRoute
  '/frequency': typeof FrequencyRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/characters': typeof CharactersRoute
  '/child': typeof ChildRoute
  '/conversation': typeof ConversationRoute
  '/devices': typeof DevicesRoute
  '/frequency': typeof FrequencyRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/overlay': typeof OverlayRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/characters'
    | '/child'
    | '/conversation'
    | '/devices'
    | '/frequency'
    | '/home'
    | '/login'
    | '/overlay'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/characters'
    | '/child'
    | '/conversation'
    | '/devices'
    | '/frequency'
    | '/home'
    | '/login'
    | '/overlay'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/characters'
    | '/child'
    | '/conversation'
    | '/devices'
    | '/frequency'
    | '/home'
    | '/login'
    | '/overlay'
    | '/parent'
    | '/profile'
    | '/progress'
    | '/register'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CharactersRoute: typeof CharactersRoute
  ChildRoute: typeof ChildRoute
  ConversationRoute: typeof ConversationRoute
  DevicesRoute: typeof DevicesRoute
  FrequencyRoute: typeof FrequencyRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OverlayRoute: typeof OverlayRoute
  ParentRoute: typeof ParentRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequency': {
      id: '/frequency'
      path: '/frequency'
      fullPath: '/frequency'
      preLoaderRoute: typeof FrequencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CharactersRoute: CharactersRoute,
  ChildRoute: ChildRoute,
  ConversationRoute: ConversationRoute,
  DevicesRoute: DevicesRoute,
  FrequencyRoute: FrequencyRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OverlayRoute: OverlayRoute,
  ParentRoute: ParentRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
